config/routes.rb
Rails.application.routes.draw do
  resources :ratings

	resources :users
	root to: 'visitors#index'
	get '/auth/:provider/callback' => 'sessions#create'
	get '/signin' => 'sessions#new', :as => :signin
	get '/signout' => 'sessions#destroy', :as => :signout
	get '/auth/failure' => 'sessions#failure'

	get 'twilio/call' => 'twilio#call'
	post '/twilio/conference_that_calls' => 'twilio#conference_that_calls'
	post '/twilio/conference_that_doesnt_call' => 'twilio#conference_that_doesnt_call'

	get 'twilio/welcome' => 'twilio#welcome'
	post '/twilio/welcome_that_calls' => 'twilio#welcome_that_calls'
	post '/twilio/welcome_that_doesnt_call' => 'twilio#welcome_that_doesnt_call'
	
	post 'twilio/voice_community' => 'twilio#voice_community'
	post 'twilio/voice_support' => 'twilio#voice_support'

	get 'connecting' => 'calls#connecting'
	get 'first' => 'calls#first'
	get '/users/:id/admin' => 'users#admin'
	get 'howitworks' => 'calls#howitworks'
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController


	def connecting
	end

  def first
    redirect_to "/together.vcf"
  end
end

app/views/calls/connecting.html.haml
%body#page1
	.row
		.col-md-4.col-md-offset-4.center
			%h1.tk-freight-sans-pro{:style => "color: #fff; padding:10px 0 0px;font-size:2.5em;"} Connecting...
			.div{:style => "padding:30px 30px 40px 30px;"}
				%p{:style => "color: #fff;text-align:left; font-size:1.2em;"} 1) Your Phone Will Ring 
				%p{:style => "color: #fff;  text-align:left; font-size:1.2em;"} 2) When you answer, we connect you to another member
				%p{:style => "color: #fff;  text-align:left; font-size:1.2em;"} 3) If they do not pick up in 60 seconds, hang up and try again.


			%p
				= link_to "Call Finished" , new_rating_path , :class => "btn btn-default btn-lg", :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 2px; font-size:1.7em; width:180px;"