config/routes.rb
Rails.application.routes.draw do
  resources :ratings

	resources :users
	root to: 'visitors#index'
	get '/auth/:provider/callback' => 'sessions#create'
	get '/signin' => 'sessions#new', :as => :signin
	get '/signout' => 'sessions#destroy', :as => :signout
	get '/auth/failure' => 'sessions#failure'

	get 'twilio/call' => 'twilio#call'
	post '/twilio/conference_that_calls' => 'twilio#conference_that_calls'
	post '/twilio/conference_that_doesnt_call' => 'twilio#conference_that_doesnt_call'

	get 'twilio/welcome' => 'twilio#welcome'
	post '/twilio/welcome_that_calls' => 'twilio#welcome_that_calls'
	post '/twilio/welcome_that_doesnt_call' => 'twilio#welcome_that_doesnt_call'
	
	post 'twilio/voice_community' => 'twilio#voice_community'
	post 'twilio/voice_support' => 'twilio#voice_support'

	get 'connecting' => 'calls#connecting'
	get 'first' => 'calls#first'
	get '/users/:id/admin' => 'users#admin'
	get 'howitworks' => 'calls#howitworks'
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.image = auth['info']['image'] || ""
         user.location = auth['info']['location'] || ""
         user.fburl = auth['info']['urls']['Facebook'] || ""
      end
    end
  end

  has_many :ratings

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index, :admin]

  def index
    @user = User.all
  end



  def show
    @user = User.find(params[:id])
    @total = Rating.where('success' => true).count
    myratings = Rating.where('user_id' => current_user.id).where('success' => true)

    @mycount = myratings.count
  end
  def edit
  	@user = User.find(params[:id])
  end
  def call
    @user = User.find(params[:id])
  end


  def admin
    @users = User.all
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  
  end

  private
    def user_params
      params.require(:user).permit(:phone, :nick, :approved)
    end

  end

app/views/users/_user.html.haml
%td= link_to user.name, user
%td= user.email
%td= link_to "edit", edit_user_path(current_user)

app/views/users/admin.html.haml
.row
	.col-sm-offset-4.col-sm-3.col-xs-8
		= link_to user_path(current_user) do
			%p.tk-swingdancer{:style => "color: #fff;font-size:2em; padding:18px 0 0px 10px;text-decoration:none; "} feel
	.col-sm-1.col-xs-4.right{:style => "padding: 10px 5px 0px;"}

		.dropdown
			%button#dropdownMenu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button",:class => "btn btn-default", :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 0px; font-size:1.7em; ",}
				%span.glyphicon.glyphicon-th-list
			%ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
				%li{:role => "presentation"}
					%a{:href => user_path(current_user), :role => "menuitem", :tabindex => "-1"} Home
				%li{:role => "presentation"}
					%a{:href => howitworks_path, :role => "menuitem", :tabindex => "-1"} How it Works
				%li{:role => "presentation"}
					%a{:href => edit_user_path(current_user), :role => "menuitem", :tabindex => "-1"} Edit Profile
				%li{:role => "presentation"}
					%a{:href => first_path, :role => "menuitem", :tabindex => "-1"} Save Contact
				- if current_user.id == 1
					%li{:role => "presentation"}
						%a{:href => '/users/1/admin', :role => "menuitem", :tabindex => "-1"} Admin

				%li.divider{:role => "presentation"}
				%li{:role => "presentation"}
					%a{:href => signout_path, :role => "menuitem", :tabindex => "-1"} Sign Out

.row
	.col-sm-4.col-md-offset-4
		%h1.tk-freight-sans-pro.center{:style => "color: #fff; padding:57px 0 50px;font-size:2.5em;"} Pending Users
		- if current_user.id == 1
			- @users.each do |u|
				%tr
					- if u.approved == false
						.col-xs-8{:style => "padding-top: 7px;font-size:1.3em; "}= link_to u.name, edit_user_path(u), :style => " color:#fff"
						.col-xs-4= link_to "Approve", edit_user_path(u), :class => "btn btn-default"
					- else 
						.col-xs-8{:style => "padding-top: 7px;font-size:1.3em;"}= link_to u.name, edit_user_path(u), :style => " color:#fff"
						.col-xs-4{:style => "margin:5px 0 5px"}= link_to u.phone, edit_user_path(u),  :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 1px"

app/views/users/edit.html.haml
.row
	.col-sm-offset-4.col-sm-3.col-xs-8
		= link_to user_path(current_user) do
			%p.tk-swingdancer{:style => "color: #fff;font-size:2em; padding:18px 0 0px 10px;text-decoration:none; "} feel
	.col-sm-1.col-xs-4.right{:style => "padding: 10px 5px 0px;"}

		.dropdown
			%button#dropdownMenu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button",:class => "btn btn-default", :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 0px; font-size:1.7em; ",}
				%span.glyphicon.glyphicon-th-list
			%ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
				%li{:role => "presentation"}
					%a{:href => user_path(current_user), :role => "menuitem", :tabindex => "-1"} Home
				%li{:role => "presentation"}
					%a{:href => howitworks_path, :role => "menuitem", :tabindex => "-1"} How it Works
				%li{:role => "presentation"}
					%a{:href => edit_user_path(current_user), :role => "menuitem", :tabindex => "-1"} Edit Profile
				%li{:role => "presentation"}
					%a{:href => first_path, :role => "menuitem", :tabindex => "-1"} Save Contact
				- if current_user.id == 1
					%li{:role => "presentation"}
						%a{:href => '/users/1/admin', :role => "menuitem", :tabindex => "-1"} Admin

				%li.divider{:role => "presentation"}
				%li{:role => "presentation"}
					%a{:href => signout_path, :role => "menuitem", :tabindex => "-1"} Sign Out
			

.row
	.col-md-4.col-md-offset-4.col-xs-10.col-xs-offset-1.box
		.profile_header.center{:style => "padding-top:77px;"} 
			= form_for @user, html: { multipart: true } do |f|
				- if @user.errors.any?
					#error_explanation
						%h2
							= pluralize(@user.errors.count, "error")
							prohibited this pin from being saved:
						%ul
							- @user.errors.full_messages.each do |msg|
								%li= msg
				.form-group.center{:style => "color:#fff;margin-bottom:23px;"} 
					= f.label "Create a nick Name", :style => "font-size:1.3em;"
					= f.text_field :nick, class: "form-control"
					%p.help-block{:style => "color:#fff;font-size:.9em;"} 
						SHARED
				.form-group.center{:style => "color:#fff;margin-bottom:20px; "} 
					= f.label "Cell Phone Number", :style => "font-size:1.3em;"
					= f.text_field :phone, class: "form-control"
					%p.help-block{:style => "color:#fff;font-size:.9em;"} 
						PRIVATE
				- if current_user.id == 1
					.checkbox
						= f.label :approved do
							= f.check_box :approved, :value => true
					

				.form-group
					= f.submit "Save Profile", class: "btn btn-default btn-lg", :style => "color:#fff;background-color:#37EC47; border-color:#fff;border-width: 2px; font-size:1.7em; margin-top:10px;width:190px; "

app/views/users/index.html.haml
.container
	.row
		.col-md-8
			%h1 boom

app/views/users/show.html.haml
.row
	.col-sm-offset-4.col-sm-3.col-xs-8
		= link_to user_path(current_user) do
			%p.tk-swingdancer{:style => "color: #fff;font-size:2em; padding:18px 0 0px 10px;text-decoration:none; "} feel
	.col-sm-1.col-xs-4.right{:style => "padding: 10px 5px 0px;"}

		.dropdown
			%button#dropdownMenu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button",:class => "btn btn-default", :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 0px; font-size:1.7em; ",}
				%span.glyphicon.glyphicon-th-list
			%ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
				%li{:role => "presentation"}
					%a{:href => user_path(current_user), :role => "menuitem", :tabindex => "-1"} Home
				%li{:role => "presentation"}
					%a{:href => howitworks_path, :role => "menuitem", :tabindex => "-1"} How it Works
				%li{:role => "presentation"}
					%a{:href => edit_user_path(current_user), :role => "menuitem", :tabindex => "-1"} Edit Profile
				%li{:role => "presentation"}
					%a{:href => first_path, :role => "menuitem", :tabindex => "-1"} Save Contact
				- if current_user.id == 1
					%li{:role => "presentation"}
						%a{:href => '/users/1/admin', :role => "menuitem", :tabindex => "-1"} Admin
					%li{:role => "presentation"}
						%a{:href => new_rating_path, :role => "menuitem", :tabindex => "-1"} Record a call
					%li{:role => "presentation"}
						%a{:href => ratings_path, :role => "menuitem", :tabindex => "-1"} View all ratings
				%li.divider{:role => "presentation"}
				%li{:role => "presentation"}
					%a{:href => signout_path, :role => "menuitem", :tabindex => "-1"} Sign Out
			



.row
	.col-md-4.col-md-offset-4.center
		- if @user.phone && @user.nick && @user.approved
			%h3.tk-freight-sans-pro{:style => "color: #fff; padding-bottom:5px;font-size:2.5em;"} Hello #{@user.nick}
			%p.center{:style => "color: #fff; padding-bottom:0px;font-size:.8em;line-height:.1em;text-decoration:underline;"} 
				%b STATUS 
			%p.center{:style => "color: #fff; padding-bottom:20px;font-size:.9em;"} Community Member 
			.row
				.col-xs-12.center
					%p.center{:style => "color: #fff; font-size:6em;line-height:80px;"}= @mycount
					%p{:style => "color: #fff; line-height:26px;margin:0; font-size:1.2em"}Connections Made


			
			%p{:style => "padding-top:40px;"}
				= link_to twilio_call_path , :class => "btn btn-default btn-lg", :style => "color:#fff;background-color:#37EC47; border-color:#fff;border-width: 2px; font-size:1.7em; width:190px;padding-right:30px;" do
					%span.glyphicon.glyphicon-earphone
					Connect
			

		- elsif @user.phone && @user.nick
			%h3.tk-freight-sans-pro{:style => "color: #fff; padding-bottom:5px;font-size:2.5em;"} Great job #{@user.nick}!
			%p{:style => "color: #fff; padding:20px 20px 15px 20px; text-align:left;font-size:1.2em;"}  
				%b Next step is to call a welcomer.
			%p{:style => "color: #fff; padding:0px 20px 25px 20px; text-align:left;font-size:1.2em;"}
				It will be a 10 min phone call and afterwards you will get access to the community.
			%p= link_to "How it Works", howitworks_path, :class => "btn btn-default btn-lg", :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 2px; font-size:1.3em;;width:190px "
			%p
				= link_to "Call Welcomer" , twilio_welcome_path , :class => "btn btn-default btn-lg", :style => "color:#fff;background-color:#37EC47; border-color:#fff;border-width: 2px; font-size:1.7em;width:190px "

		- else
			%h3.tk-freight-sans-pro{:style => "color: #fff; padding-bottom:5px;font-size:2.5em;"}Welcome! 
			%p{:style => "color: #fff; padding:20px 20px 15px 20px; text-align:left;font-size:1.2em;"}  
				%b First step is to create a profile.
			%p{:style => "color: #fff; padding:0 20px 25px 20px; text-align:left;font-size:1.2em;"}   
				This includes your "Nick Name" which you will use when connecting. This can be your name or any name you like. 
			%p
				= link_to "How it Works", howitworks_path, :class => "btn btn-default btn-lg", :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 2px; font-size:1.3em; width:190px; "
			%p
				= link_to "Create Profile", edit_user_path(@user), :class => "btn btn-default btn-lg", :style => "color:#fff;background-color:#37EC47; border-color:#fff;border-width: 2px; font-size:1.7em; width:190px; "