config/routes.rb
Rails.application.routes.draw do
  resources :ratings

	resources :users
	root to: 'visitors#index'
	get '/auth/:provider/callback' => 'sessions#create'
	get '/signin' => 'sessions#new', :as => :signin
	get '/signout' => 'sessions#destroy', :as => :signout
	get '/auth/failure' => 'sessions#failure'

	get 'twilio/call' => 'twilio#call'
	post '/twilio/conference_that_calls' => 'twilio#conference_that_calls'
	post '/twilio/conference_that_doesnt_call' => 'twilio#conference_that_doesnt_call'

	get 'twilio/welcome' => 'twilio#welcome'
	post '/twilio/welcome_that_calls' => 'twilio#welcome_that_calls'
	post '/twilio/welcome_that_doesnt_call' => 'twilio#welcome_that_doesnt_call'
	
	post 'twilio/voice_community' => 'twilio#voice_community'
	post 'twilio/voice_support' => 'twilio#voice_support'

	get 'connecting' => 'calls#connecting'
	get 'first' => 'calls#first'
	get '/users/:id/admin' => 'users#admin'
	get 'howitworks' => 'calls#howitworks'
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :user_id
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = current_user.ratings.build
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = current_user.ratings.build(rating_params)
    @user = current_user
    respond_to do |format|
      if @rating.save
        format.html { redirect_to user_path(@user)}
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    def correct_user
      @rating = current_user.ratings.find_by(id: params[:id])
      redirect_to ratings_path, notice: "Hey! Pick on your own rating :)" if @rating.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:success, :user_id, :favorite, :safety)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.haml
= form_for @rating do |f|
	- if @rating.errors.any?
		#error_explanation
			%h2= "#{pluralize(@rating.errors.count, "error")} prohibited this rating from being saved:"
			%ul
				- @rating.errors.full_messages.each do |msg|
					%li= msg
	.field
		%p{:style => "color: #fff;  font-size:1.2em;"}  Did you Connect?
		%span{:style => "padding: 20px;font-size:1.4em; color:#fff"}
			= f.radio_button :success, false, :checked => "checked"
			= f.label "No"
		%span{:style => "padding: 20px;font-size:1.4em; color:#fff"}
			= f.radio_button :success, true
			= f.label "Yes"
		%p{:style => "color: #fff;  font-size:1.2em; padding-top:20px"}  Favorite this Member?
		%span{:style => "padding: 20px;font-size:1.4em; color:#fff"}
			= f.radio_button :favorite, false, :checked => "checked"
			= f.label "No"
		%span{:style => "padding: 20px;font-size:1.4em; color:#fff"}
			= f.radio_button :favorite, true
			= f.label "Yes"
		%p{:style => "color: #fff; font-size:1.2em; padding-top:20px"}  Safety Violations?
		%span{:style => "padding: 20px;font-size:1.4em; color:#fff"}
			= f.radio_button :safety, false, :checked => "checked"
			= f.label "No"
		%span{:style => "padding: 20px;font-size:1.4em; color:#fff"}
			= f.radio_button :safety, true
			= f.label "Yes"

	.actions{:style => "padding: 30px;"}
		= f.submit 'Continue',  :class => "btn btn-default btn-lg", :style => "color:#fff;background-color:#58CEEE; border-color:#fff;border-width: 2px; font-size:1.7em; width:180px;"
	

app/views/ratings/edit.html.haml
%h1 Editing rating

= render 'form'

= link_to 'Show', @rating
\|
= link_to 'Back', ratings_path

app/views/ratings/index.html.haml
.row
	.col-md-4.col-md-offset-4
		.center
			%h1{:style => "color:#fff"}
				= @ratings.count
				Calls Made
		%table{:style => "width: 100%;color:#fff"}
			%tr
				%th Success
				%th Safety
				%th Favorite
				%th User
				%th Created

			- @ratings.each do |rating|
				%tr
					%td= rating.success
					%td= rating.safety
					%td= rating.favorite
					%td= rating.user_id
					%td= time_ago_in_words(rating.created_at)

app/views/ratings/new.html.haml
%body#page1
	.row
		.col-md-4.col-md-offset-4.center
			%h1.tk-freight-sans-pro{:style => "color: #fff; padding:10px 0 20px;font-size:2.5em;"} How was the call?
			= render 'form'

app/views/ratings/show.html.haml
%p#notice= notice

%p
  %b Success:
  = @rating.success

= link_to 'Edit', edit_rating_path(@rating)
\|
= link_to 'Back', ratings_path